### PR TITLE
(NB: theres some redudancy in the encoding for now) migrating the lookup structures for Unicode/ToTex.hs to use C source fil...

### PR DESCRIPTION
**Pull request by cartazio**
...es to accelerate builds

theres  A HUGE amount of redudancy / lack of sharing in how i encoding the lookup structures, but its was simpler to write that way.

Moving to a cleverer encoding (just just adding an extra layer of indirect to have better sharing) would shrink the side of the resulting 
object code a teeny bit.

all thats left is the entity map PR, which is even simpler than this one.

Bear in mine, it has only typed check, not test :)

### CODE REVIEW

**Comment by cartazio** [comment]
boo, its failing the tests

**Comment by cartazio** [comment]
OHHH, i understand whats happening, 

consider 
```
 , Record {uchar = 'B', commands = [("base","B"),("base","\\mathrm{B}"),("unicode-math","")], category = Alpha, comments = "LATIN CAPITAL LETTER B"}
```

i'm not preserving the ordering semantics of the commands list!

**Comment by cartazio** [comment]
ok, simply adding a reverse to how I constructed the map solved that :) .
just force pushed an update to the PR that should pass the test sutie

**Comment by jgm** [comment]
Missing piece is a script to construct the cbits programatically.
(From what?  Now I can't remember what the source of that big list of haskell records was -- maybe @mpickering remembers?)

**Comment by mpickering** [comment]
There are scripts which generated the haskell files in the `lib` directory.

**Comment by cartazio** [comment]
should we close this PR though and have a ticket just for that? :)

**Comment by jgm** [comment]
Maybe, but this PR should still be preserved and linked to, because it
shows what the generated cbits should look like.

+++ Carter Tazio Schonwald [Feb 25 17 14:55 ]:

**Comment by cartazio** [comment]
Might Be more robust to include the reference files in the test or data
dir. or some reference branch on the main repo.   else any accidental repo
spring cleaning on my side could clober it

**Comment by jgm** [comment]
OK, I've merged this into a `morecbits` branch in this repository, so I'll close the PR.

**Pull request closed without merging**
