### PR TITLE
TeX: support `\xleftarrow` and `\xrightarrow`

### PR DESCRIPTION
**Pull request by tarleb**

### CODE REVIEW

**Comment by tarleb** [comment]
Converting to draft: the omml writer gives bad results when converting `\xrightarrow{...}`.

**Comment by tarleb** [comment]
It looks like LibreOffice has only a very limited support for the `nary` element. I've added a commit which uses `nary` only if we know that it will yield good results.

See the relevant part of the LibreOffice [docx importer](https://github.com/LibreOffice/core/blob/master/starmath/source/ooxmlimport.cxx#L534-L566).

**Comment by jgm** [comment]
In the writer the use of xleftarrow/xrightarrow should be sensitive to the Env
(use only if it includes "amsmath").
For an example see the code of writeBinom.

**Comment by tarleb** [comment]
Thanks. Should be fixed now.

**Pull request merged**
